/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.treeangle;
import java.util.Scanner;
public class App {
    
    public static void main(String[] args) {
      double alas, tinggi, luas, keliling;
      int pilihan;
      Scanner input = new Scanner(System.in);
      
      System.out.print("masukan nilai alas =");
      alas = input.nextInt();
      
      System.out.print("masukan nilai tinggi ="); 
      tinggi = input.nextInt();
      
      
      System.out.print("luas atau keliling 1|2 ");
      pilihan = input.nextInt();
      
      if(pilihan == 1){
         luas = 0.5 * tinggi * alas;
         System.out.println("luas segitiga adalah = " + luas);
      } else if (pilihan == 2){
         keliling = 3 * alas;
         System.out.println("keliling segitiga adalah = " + keliling);
      } else{
         System.out.println("jawaban tidak valid silahkan coba lagi");
      }
     
      
      
    }    
}
